<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.yuegang.zhihui</groupId>
        <artifactId>ygh-product</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>ygh-product-service</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.yuegang.zhihui</groupId>
            <artifactId>ygh-product-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.yuegang.zhihui</groupId>
            <artifactId>ygh-search-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.yuegang.zhihui</groupId>
            <artifactId>ygh-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.yuegang.zhihui</groupId>
            <artifactId>ygh-common-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.yuegang.zhihui</groupId>
            <artifactId>ygh-common-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.yuegang.zhihui</groupId>
            <artifactId>ygh-common-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.yuegang.zhihui</groupId>
            <artifactId>ygh-common-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.yuegang.zhihui</groupId>
            <artifactId>ygh-common-mq</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.yuegang.zhihui</groupId>
            <artifactId>ygh-common-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
