package com.yuegang.zhihui.knowledge.application;
import static org.assertj.core.api.Assertions.*;import com.fasterxml.jackson.databind.ObjectMapper;import com.yuegang.zhihui.common.core.BusinessException;import com.yuegang.zhihui.common.test.YghTestContainerFactory;import java.nio.file.*;import java.util.Base64;import org.flywaydb.core.Flyway;import org.junit.jupiter.api.Test;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.*;
class KnowledgeJobRecoveryIntegrationTest{
 @Test void queriesRetriesAndRecoversParseAndIndexJobsAndWiresConfiguration()throws Exception{try(var mysql=YghTestContainerFactory.mysql().start()){
  Flyway.configure().dataSource(mysql.jdbcUrl(),mysql.username(),mysql.credential()).locations("classpath:db/migration").load().migrate();var dataSource=new DriverManagerDataSource(mysql.jdbcUrl(),mysql.username(),mysql.credential());var jdbc=new JdbcTemplate(dataSource);Path root=Files.createTempDirectory("knowledge-jobs");Files.writeString(root.resolve("1.bin"),"跨境政策解析恢复内容");jdbc.update("INSERT INTO knowledge_document(id,title,category,file_name,media_type,size_bytes,sha256,storage_key,status,uploaded_by) VALUES(1,'政策','POLICY','a.md','text/markdown',30,REPEAT('a',64),'1.bin','PROCESSING',7)");jdbc.update("INSERT INTO knowledge_processing_job(id,document_id,task_type,status,progress,retry_count,last_error) VALUES(11,1,'PARSE','FAILED',0,10,'parse failed')");jdbc.update("INSERT INTO knowledge_index_job(id,document_id,index_version,job_type,status,retry_count,last_error) VALUES(12,1,'v1','UPSERT','FAILED',10,'index failed')");
  var parser=new KnowledgeParseDispatcher(dataSource,root.toString());var processing=new KnowledgeProcessingJobService(dataSource,parser);assertThat(processing.list("1","FAILED",50)).singleElement().satisfies(job->assertThat(job.failureReason()).contains("parse failed"));assertThat(processing.retry("11").status()).isEqualTo("SUCCEEDED");assertThatThrownBy(()->processing.retry("bad")).isInstanceOf(BusinessException.class);
  var indexes=new KnowledgeIndexJobService(dataSource);assertThat(indexes.list("1","FAILED",50)).singleElement().satisfies(job->assertThat(job.retryCount()).isEqualTo(10));assertThat(indexes.retry("12").status()).isEqualTo("RETRY");assertThatThrownBy(()->indexes.retry("12")).isInstanceOf(BusinessException.class);
  jdbc.update("UPDATE knowledge_document SET status='PUBLISHED' WHERE id=1");
  assertThat(indexes.rebuild("knowledge-recovery-v2").queuedDocuments()).isEqualTo(1);
  assertThat(indexes.rebuild("knowledge-recovery-v2").queuedDocuments()).isZero();
  assertThat(indexes.list("1","PENDING",50)).singleElement().satisfies(job->assertThat(job.indexVersion()).isEqualTo("knowledge-recovery-v2"));
  assertThatThrownBy(()->indexes.rebuild("INVALID VERSION")).isInstanceOf(BusinessException.class);
  var configuration=new KnowledgeConfiguration();var json=new ObjectMapper();var transactions=new DataSourceTransactionManager(dataSource);String secret=Base64.getEncoder().encodeToString("01234567890123456789012345678901".getBytes());assertThat(configuration.knowledgeParseDispatcher(dataSource,root.toString())).isNotNull();assertThat(configuration.knowledgeDocumentService(dataSource,root.toString(),parser)).isNotNull();assertThat(configuration.knowledgeLifecycleService(dataSource)).isNotNull();assertThat(configuration.knowledgeMetadataService(dataSource,json)).isNotNull();assertThat(configuration.knowledgeIndexJobService(dataSource)).isNotNull();assertThat(configuration.knowledgeProcessingJobService(dataSource,parser)).isNotNull();assertThat(configuration.knowledgeExpiryJob(jdbc,transactions)).isNotNull();assertThat(configuration.knowledgeIndexDispatcher(jdbc,"http://127.0.0.1:1",secret)).isNotNull();assertThat(configuration.knowledgeUserResolver(secret)).isNotNull();
 }finally{}}
}
