package com.yuegang.zhihui.system.application;
import static org.assertj.core.api.Assertions.*;import com.yuegang.zhihui.common.core.BusinessException;import com.yuegang.zhihui.common.test.YghTestContainerFactory;import com.yuegang.zhihui.system.api.*;import java.util.*;import org.flywaydb.core.Flyway;import org.junit.jupiter.api.Test;import org.springframework.jdbc.datasource.DriverManagerDataSource;
class RoleAdministrationServiceTest{
 @Test void managesPermissionCatalogAndOptimisticallyVersionedRoles(){try(var mysql=YghTestContainerFactory.mysql().start()){
  Flyway.configure().dataSource(mysql.jdbcUrl(),mysql.username(),mysql.credential()).locations("classpath:db/migration").load().migrate();var dataSource=new DriverManagerDataSource(mysql.jdbcUrl(),mysql.username(),mysql.credential());
  var configuration=new SystemConfiguration();var clock=configuration.systemClock();var repository=configuration.authorizationRepository(dataSource);assertThat(configuration.authorizationService(repository)).isNotNull();assertThat(configuration.roleAdministrationService(dataSource)).isNotNull();assertThat(configuration.systemSettingService(dataSource)).isNotNull();assertThat(configuration.systemCatalogService(dataSource)).isNotNull();assertThat(configuration.systemDictionaryAdministrationService(dataSource)).isNotNull();String secret=Base64.getEncoder().encodeToString("01234567890123456789012345678901".getBytes());assertThat(configuration.systemTrustedUserContextResolver(secret,clock)).isNotNull();assertThat(configuration.internalServiceVerifier(secret,clock)).isNotNull();
  var service=new RoleAdministrationService(dataSource);assertThat(service.roles()).hasSize(3);assertThat(service.permissions()).hasSize(4);var permission=service.savePermission("knowledge:review",new UpsertPermissionRequest("knowledge:review","审核知识","KNOWLEDGE",true));assertThat(permission.enabled()).isTrue();var created=service.saveRole("REVIEWER",new UpsertRoleRequest("REVIEWER","知识审核员",Set.of("knowledge:review"),true,0));assertThat(created.permissions()).containsExactly("knowledge:review");var updated=service.saveRole("REVIEWER",new UpsertRoleRequest("REVIEWER","高级审核员",Set.of(),true,created.version()));assertThat(updated.name()).isEqualTo("高级审核员");assertThatThrownBy(()->service.saveRole("WRONG",new UpsertRoleRequest("REVIEWER","x",Set.of(),true,0))).isInstanceOf(BusinessException.class);assertThatThrownBy(()->service.saveRole("BAD_ROLE",new UpsertRoleRequest("BAD_ROLE","x",Set.of("missing:permission"),true,0))).isInstanceOf(BusinessException.class);
 }}
}
