<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';import { Delete } from '@element-plus/icons-vue';import { ElMessage } from 'element-plus';import PageHeader from '@/components/PageHeader.vue';import { listCartItems,removeCartItem,saveCartItem,type CartItem } from '@/api/cart';import { getProduct,type Product } from '@/api/product'
type Line={cart:CartItem;product:Product};const loading=ref(true);const lines=ref<Line[]>([])
const selected=computed(()=>lines.value.filter(x=>x.cart.selected));const total=computed(()=>selected.value.reduce((sum,x)=>sum+Number(x.product.price)*x.cart.quantity,0).toFixed(2))
async function load(){loading.value=true;try{const items=await listCartItems();const products=await Promise.all(items.map(x=>getProduct(x.skuId)));lines.value=items.map((cart,index)=>({cart,product:products[index]!}))}catch{ElMessage.error('购物车加载失败')}finally{loading.value=false}}
async function update(line:Line){try{line.cart=await saveCartItem({skuId:line.cart.skuId,quantity:line.cart.quantity,selected:line.cart.selected,version:line.cart.version})}catch{ElMessage.error('购物车已变化，正在刷新');await load()}}
async function remove(line:Line){try{await removeCartItem(line.cart);lines.value=lines.value.filter(x=>x.cart.id!==line.cart.id)}catch{ElMessage.error('删除失败，正在刷新');await load()}}
async function selectAll(value:unknown){for(const line of lines.value){if(line.cart.selected!==Boolean(value)){line.cart.selected=Boolean(value);await update(line)}}}
onMounted(load)
</script>
<template><PageHeader title="购物车" description="确认商品、规格与数量后进入订单预览。库存和价格将在服务端重新校验。"/><div v-loading="loading" class="paper-card cart"><div class="cart-head"><el-checkbox :model-value="selected.length===lines.length&&lines.length>0" @change="selectAll">全选</el-checkbox><span>商品信息</span><span>单价</span><span>数量</span><span>小计</span><span>操作</span></div><div v-for="line in lines" :key="line.cart.id" class="cart-line"><el-checkbox v-model="line.cart.selected" @change="update(line)"/><div class="goods"><div class="thumb">{{line.product.name.slice(0,1)}}</div><div><b>{{line.product.name}}</b><small>{{Object.entries(line.product.specifications).map(([k,v])=>`${k} ${v}`).join(' · ')}}</small></div></div><span>¥{{Number(line.product.price).toFixed(2)}}</span><el-input-number v-model="line.cart.quantity" :min="1" :max="999" size="small" @change="update(line)"/><b class="price">¥{{(Number(line.product.price)*line.cart.quantity).toFixed(2)}}</b><el-button text :icon="Delete" @click="remove(line)"/></div><div v-if="!loading&&!lines.length" class="empty-state">购物车还是空的，去商城挑选商品吧。</div></div><div class="checkout-bar paper-card"><span>已选择 <b>{{selected.length}}</b> 种商品</span><div>合计：<strong>¥{{total}}</strong><small>不含真实运费</small></div><el-button size="large" type="primary" :disabled="!selected.length" @click="$router.push('/workspace/checkout')">去结算</el-button></div></template>
<style scoped>.cart{overflow:hidden;min-height:180px}.cart-head,.cart-line{display:grid;grid-template-columns:45px minmax(280px,1fr) 100px 150px 110px 60px;align-items:center;padding:15px 20px}.cart-head{background:#edf2ed;color:var(--muted);font-size:12px}.cart-line{border-top:1px solid var(--line);font-size:13px}.goods{display:flex;align-items:center;gap:12px}.goods b,.goods small{display:block}.goods small{margin-top:5px;color:var(--muted)}.thumb{width:58px;height:58px;display:grid;place-items:center;background:var(--jade-soft);color:var(--jade);font:700 22px serif}.checkout-bar{display:flex;align-items:center;justify-content:flex-end;gap:30px;margin-top:16px;padding:15px 20px}.checkout-bar>span{margin-right:auto}.checkout-bar strong,.checkout-bar small{display:block;text-align:right}.checkout-bar strong{color:var(--cinnabar);font-size:22px}.checkout-bar small{color:var(--muted)}@media(max-width:850px){.cart{overflow:auto}.cart-head,.cart-line{min-width:850px}}</style>
