<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';import { useRouter } from 'vue-router';import { ElMessage } from 'element-plus';import PageHeader from '@/components/PageHeader.vue';import { listMyAddresses,type Address } from '@/api/user';import { listCartItems } from '@/api/cart';import { getProduct,type Product } from '@/api/product';import { createOrder,previewOrder,type CreateOrderCommand,type OrderPreview } from '@/api/order'
type Line={skuId:string;quantity:number;product:Product};const router=useRouter();const loading=ref(true);const submitting=ref(false);const addressId=ref('');const addresses=ref<Address[]>([]);const lines=ref<Line[]>([]);const remark=ref('');const preview=ref<OrderPreview>()
const selectedAddress=computed(()=>addresses.value.find(x=>x.id===addressId.value));
function command():CreateOrderCommand{const a=selectedAddress.value;if(!a)throw new Error('address required');return{requestId:crypto.randomUUID(),items:lines.value.map(x=>({skuId:x.skuId,skuCode:x.product.skuCode,productName:x.product.name,unitPrice:x.product.price,quantity:x.quantity})),address:{recipientName:a.recipientName,recipientPhone:a.recipientPhone,countryCode:a.countryCode,provinceCode:a.provinceCode,provinceName:a.provinceName,cityName:a.cityName,districtName:a.districtName,addressDetail:a.addressDetail,postalCode:a.postalCode},remark:remark.value||undefined}}
async function refreshPreview(){if(!selectedAddress.value||!lines.value.length)return;try{preview.value=await previewOrder(command())}catch{ElMessage.error('结算预览失败，商品价格或状态可能已变化')}}
async function load(){loading.value=true;try{addresses.value=await listMyAddresses();addressId.value=(addresses.value.find(x=>x.defaultAddress)||addresses.value[0])?.id||'';const cart=(await listCartItems()).filter(x=>x.selected);const products=await Promise.all(cart.map(x=>getProduct(x.skuId)));lines.value=cart.map((x,i)=>({skuId:x.skuId,quantity:x.quantity,product:products[i]!}));await refreshPreview()}catch{ElMessage.error('结算信息加载失败')}finally{loading.value=false}}
async function submit(){submitting.value=true;try{const order=await createOrder(command());ElMessage.success('模拟订单已创建');await router.push(`/workspace/orders/${order.orderId}`)}catch{ElMessage.error('订单创建失败，请重新预览结算信息')}finally{submitting.value=false}}
onMounted(load)
</script>
<template><div v-loading="loading"><PageHeader title="确认订单" description="服务端将生成地址快照与商品快照，支付使用虚拟余额。"/><div class="checkout-grid"><main><section class="paper-card block"><h3 class="serif">收货地址</h3><el-radio-group v-model="addressId" class="addresses" @change="refreshPreview"><el-radio v-for="a in addresses" :key="a.id" :value="a.id" border><b>{{a.recipientName}} {{a.recipientPhone}}</b><span>{{a.provinceName}}{{a.cityName}}{{a.districtName}}{{a.addressDetail}}</span><el-tag v-if="a.defaultAddress" size="small">默认</el-tag></el-radio></el-radio-group><el-empty v-if="!addresses.length" description="请先添加收货地址"/><el-button text @click="$router.push('/workspace/addresses')">管理收货地址</el-button></section><section class="paper-card block"><h3 class="serif">商品清单</h3><div v-for="line in lines" :key="line.skuId" class="order-item"><span class="thumb">{{line.product.name.slice(0,1)}}</span><div><b>{{line.product.name}}</b><small>{{line.product.skuCode}}</small></div><span>¥{{Number(line.product.price).toFixed(2)}} × {{line.quantity}}</span><b>¥{{(Number(line.product.price)*line.quantity).toFixed(2)}}</b></div><el-empty v-if="!lines.length" description="没有选中的商品"/></section><section class="paper-card block"><h3 class="serif">订单备注</h3><el-input v-model="remark" type="textarea" maxlength="200" show-word-limit placeholder="选填，请勿填写敏感个人信息"/></section></main><aside class="paper-card summary"><h3 class="serif">结算摘要</h3><p><span>商品金额</span><b>¥{{Number(preview?.totalAmount||0).toFixed(2)}}</b></p><p><span>模拟运费</span><b>¥0.00</b></p><el-alert v-if="preview?.warnings.length" :title="preview.warnings.join('；')" type="warning" :closable="false"/><p class="total"><span>应付金额</span><strong>¥{{Number(preview?.totalAmount||0).toFixed(2)}}</strong></p><el-alert title="虚拟支付" description="不会扣除真实资金，也不会真实发货。" type="warning" :closable="false"/><el-button size="large" type="primary" :loading="submitting" :disabled="!preview||!lines.length||!addressId" @click="submit">提交模拟订单</el-button></aside></div></div></template>
<style scoped>.checkout-grid{display:grid;grid-template-columns:1fr 320px;gap:20px}.block{padding:22px;margin-bottom:16px}.block h3,.summary h3{margin-top:0}.addresses{width:100%;display:grid;gap:10px}.addresses .el-radio{height:auto;margin:0;padding:15px}.addresses b,.addresses span{margin-right:12px}.order-item{display:grid;grid-template-columns:55px 1fr 150px 90px;align-items:center;gap:12px;padding:14px 0;border-top:1px solid var(--line)}.thumb{width:48px;height:48px;display:grid;place-items:center;background:var(--jade-soft);color:var(--jade);font-weight:700}.order-item small{display:block;margin-top:4px;color:var(--muted)}.summary{height:max-content;padding:24px;position:sticky;top:24px}.summary p{display:flex;justify-content:space-between}.summary p span{color:var(--muted)}.summary .total{margin-top:20px;padding-top:18px;border-top:1px solid var(--line)}.summary strong{color:var(--cinnabar);font-size:24px}.summary .el-button{width:100%;margin-top:18px}@media(max-width:800px){.checkout-grid{grid-template-columns:1fr}.summary{position:static}}</style>
