<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '@/components/PageHeader.vue'
import { cancelOrder, getOrder, payOrder, requestOrderRefund, type Order } from '@/api/order'
const route=useRoute();const loading=ref(true);const acting=ref(false);const order=ref<Order>()
const names:Record<string,string>={PENDING_PAYMENT:'待支付',PAID:'已支付',PROCESSING:'处理中',COMPLETED:'已完成',CANCELLED:'已取消',CLOSED:'已关闭',REFUNDING:'退款中',REFUND_REQUESTED:'退款中',REFUNDED:'已退款'}
const step=computed(()=>order.value?.status==='PENDING_PAYMENT'?1:['PAID','PROCESSING'].includes(order.value?.status||'')?2:3)
async function load(){loading.value=true;try{order.value=await getOrder(String(route.params.id))}catch{ElMessage.error('订单详情加载失败')}finally{loading.value=false}}
async function act(action:'pay'|'cancel'|'refund'){if(!order.value)return;await ElMessageBox.confirm(`确认执行${action==='pay'?'模拟支付':action==='cancel'?'取消订单':'申请退款'}？`,'订单操作确认');acting.value=true;try{if(action==='pay')order.value=await payOrder(order.value);else order.value=action==='cancel'?await cancelOrder(order.value):await requestOrderRefund(order.value);if(action==='pay'&&order.value.status==='PAID')ElMessage.success('模拟支付成功，订单已结清');else if(action==='pay')ElMessage.warning(`订单当前为${names[order.value.status]||order.value.status}，未执行新的扣款`);else ElMessage.success('订单操作已受理');await load()}catch(error){ElMessage.error(error instanceof Error?error.message:'订单操作失败，请刷新状态后重试')}finally{acting.value=false}}
onMounted(load)
</script>
<template><div v-loading="loading"><PageHeader title="订单详情" :description="`订单号 ${order?.orderNo||'--'}`"/><el-alert :title="`当前状态：${names[order?.status||'']||order?.status||'--'}`" description="本平台只执行模拟支付和模拟履约，不产生真实物流。" :type="order?.status==='PENDING_PAYMENT'?'warning':'info'" show-icon :closable="false"/><div class="paper-card timeline"><el-steps :active="step" finish-status="success"><el-step title="提交订单" :description="order?new Date(order.createdAt).toLocaleString('zh-CN'):''"/><el-step title="模拟支付" :description="order?.status==='PENDING_PAYMENT'?'等待支付':'已处理'"/><el-step title="业务完成" description="不产生真实物流"/></el-steps></div><div class="detail-columns"><section class="paper-card"><h3 class="serif">订单事实</h3><p><b>订单 ID：</b>{{order?.orderId}}</p><p><b>订单版本：</b>{{order?.version}}</p><p><b>币种：</b>{{order?.currency}}</p></section><section class="paper-card"><h3 class="serif">支付信息</h3><p><b>支付方式：</b>模拟钱包余额</p><p><b>应付金额：</b><strong>¥{{Number(order?.totalAmount||0).toFixed(2)}}</strong></p><el-button v-if="order?.status==='PENDING_PAYMENT'" type="primary" :loading="acting" @click="act('pay')">立即模拟支付</el-button><el-button v-if="order?.status==='PENDING_PAYMENT'" :loading="acting" @click="act('cancel')">取消订单</el-button><el-button v-if="['PAID','COMPLETED'].includes(order?.status||'')" type="warning" :loading="acting" @click="act('refund')">申请模拟退款</el-button></section></div></div></template>
<style scoped>.timeline{padding:28px;margin:18px 0}.detail-columns{display:grid;grid-template-columns:1fr 1fr;gap:18px}.detail-columns section{padding:22px}.detail-columns strong{color:var(--cinnabar);font-size:20px}@media(max-width:700px){.detail-columns{grid-template-columns:1fr}}</style>
