<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import PageHeader from '@/components/PageHeader.vue'
import { listMyOrders, payOrder, type Order } from '@/api/order'
const tab=ref('ALL');const loading=ref(true);const paying=ref<string>();const orders=ref<Order[]>([])
const tabs=[['全部','ALL'],['待支付','PENDING_PAYMENT'],['已支付','PAID'],['已完成','COMPLETED'],['退款','REFUNDED']]
const names:Record<string,string>={PENDING_PAYMENT:'待支付',PAID:'已支付',PROCESSING:'处理中',COMPLETED:'已完成',CANCELLED:'已取消',CLOSED:'已关闭',REFUNDING:'退款中',REFUND_REQUESTED:'退款中',REFUNDED:'已退款'}
const visible=computed(()=>tab.value==='ALL'?orders.value:orders.value.filter(x=>x.status===tab.value))
async function load(){loading.value=true;try{orders.value=await listMyOrders()}catch{ElMessage.error('订单列表加载失败')}finally{loading.value=false}}
async function pay(order:Order){paying.value=order.orderId;try{const updated=await payOrder(order);const index=orders.value.findIndex(x=>x.orderId===updated.orderId);if(index>=0)orders.value[index]=updated;if(updated.status==='PAID')ElMessage.success('模拟支付成功，订单已结清');else ElMessage.warning(`订单当前为${names[updated.status]||updated.status}，未执行新的扣款`);await load()}catch(error){ElMessage.error(error instanceof Error?error.message:'模拟支付失败，请检查余额或订单状态')}finally{paying.value=undefined}}
onMounted(load)
</script>
<template><PageHeader title="我的订单" description="查看订单状态与模拟支付、退款记录。"/><div v-loading="loading" class="paper-card orders"><el-tabs v-model="tab"><el-tab-pane v-for="item in tabs" :key="item[1]" :label="item[0]" :name="item[1]"/></el-tabs><el-empty v-if="!loading&&!visible.length" description="暂无订单"/><article v-for="order in visible" :key="order.orderId"><header><span>{{new Date(order.createdAt).toLocaleString('zh-CN')}}</span><b>订单号 {{order.orderNo}}</b><el-tag :type="order.status==='PENDING_PAYMENT'?'warning':order.status==='PAID'?'success':'info'">{{names[order.status]||order.status}}</el-tag></header><div><span class="thumb">粤</span><div><b>跨境商城订单</b><small>订单数据为交易快照，不随商品修改而改变</small></div><strong>¥{{Number(order.totalAmount).toFixed(2)}}</strong><div class="actions"><el-button size="small" @click="$router.push(`/workspace/orders/${order.orderId}`)">订单详情</el-button><el-button v-if="order.status==='PENDING_PAYMENT'" size="small" type="primary" :loading="paying===order.orderId" @click="pay(order)">立即支付</el-button></div></div></article></div></template>
<style scoped>.orders{padding:20px}.filter{display:flex;gap:10px;margin-bottom:18px}.filter .el-input{width:260px}.orders article{margin-top:12px;border:1px solid var(--line)}.orders article header{display:flex;align-items:center;gap:18px;padding:10px 14px;background:#f1f3ee;color:var(--muted);font-size:12px}.orders article header b{color:var(--ink)}.orders article header .el-tag{margin-left:auto}.orders article>div{display:grid;grid-template-columns:60px 1fr 120px 160px;align-items:center;gap:14px;padding:18px}.thumb{width:55px;height:55px;display:grid;place-items:center;background:var(--jade-soft);color:var(--jade);font-weight:700}.orders article small{display:block;margin-top:5px;color:var(--muted)}.orders article strong{color:var(--cinnabar);font-size:17px}.actions{text-align:right}@media(max-width:750px){.filter{flex-wrap:wrap}.orders article>div{grid-template-columns:55px 1fr}.actions{text-align:left}.orders article>div>strong{grid-column:2}}</style>
