package com.yuegang.zhihui.knowledge.application;
import com.yuegang.zhihui.common.security.InternalServiceSignature;import com.yuegang.zhihui.search.api.*;import java.time.*;import java.util.List;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.web.client.RestClient;
public final class KnowledgeIndexDispatcher{
 private static final String INDEX="/internal/v1/search/index",DELETE="/internal/v1/search/delete-document";private final JdbcTemplate jdbc;private final RestClient search;private final InternalServiceSignature signatures;
 public KnowledgeIndexDispatcher(JdbcTemplate jdbc,String baseUrl,byte[] secret){this.jdbc=jdbc;search=RestClient.builder().baseUrl(baseUrl).build();signatures=new InternalServiceSignature(secret,Clock.systemUTC(),Duration.ofSeconds(30));}
 @Scheduled(fixedDelayString="${ygh.knowledge.index-dispatch-delay:5000}")public void dispatch(){List<Long>jobs=jdbc.queryForList("SELECT id FROM knowledge_index_job WHERE status IN ('PENDING','RETRY') AND (next_retry_at IS NULL OR next_retry_at<=NOW(6)) ORDER BY created_at LIMIT 10",Long.class);for(long job:jobs)process(job);}
 private void process(long job){if(jdbc.update("UPDATE knowledge_index_job SET status='PROCESSING' WHERE id=? AND status IN ('PENDING','RETRY')",job)!=1)return;try{var metadata=jdbc.query("SELECT j.document_id,j.index_version,j.job_type,d.title,d.category,d.visibility,d.status,d.version,d.updated_at FROM knowledge_index_job j JOIN knowledge_document d ON d.id=j.document_id WHERE j.id=?",r->{r.next();return new Metadata(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getLong(8),r.getTimestamp(9).toLocalDateTime().atOffset(ZoneOffset.UTC));},job);if("DELETE".equals(metadata.jobType()))send(DELETE,new DeleteDocumentCommand(Long.toString(metadata.documentId())));else{if(!"PUBLISHED".equals(metadata.status()))throw new IllegalStateException("document is no longer published");jdbc.query("SELECT id,content FROM knowledge_chunk WHERE document_id=? AND status='ACTIVE' ORDER BY chunk_index",r->{send(INDEX,new IndexChunkCommand(Long.toString(metadata.documentId()),Long.toString(r.getLong(1)),metadata.title(),r.getString(2),metadata.category(),metadata.visibility(),metadata.indexVersion(),metadata.documentVersion(),metadata.updatedAt(),true));},metadata.documentId());}jdbc.update("UPDATE knowledge_index_job SET status='SUCCEEDED',last_error=NULL WHERE id=?",job);}catch(RuntimeException failure){String error=failure.getClass().getSimpleName()+": "+String.valueOf(failure.getMessage());jdbc.update("UPDATE knowledge_index_job SET status=CASE WHEN retry_count>=9 THEN 'FAILED' ELSE 'RETRY' END,retry_count=retry_count+1,next_retry_at=DATE_ADD(NOW(6),INTERVAL LEAST(300,POW(2,retry_count)) SECOND),last_error=? WHERE id=?",error.substring(0,Math.min(1000,error.length())),job);}}
 private void send(String path,Object command){Instant now=Instant.now();var metadata=new InternalServiceSignature.Metadata("ygh-knowledge-service","POST",path,now);search.post().uri(path).header("X-YGH-Service","ygh-knowledge-service").header("X-YGH-Service-Timestamp",Long.toString(now.toEpochMilli())).header("X-YGH-Service-Signature",signatures.sign(metadata)).body(command).retrieve().toBodilessEntity();}
 private record Metadata(long documentId,String indexVersion,String jobType,String title,String category,String visibility,String status,long documentVersion,OffsetDateTime updatedAt){}
}
