package com.yuegang.zhihui.ai.infrastructure;
import com.fasterxml.jackson.databind.ObjectMapper;import com.yuegang.zhihui.common.core.ApiResponse;import com.yuegang.zhihui.common.security.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.*;import org.springframework.web.client.RestClient;
public final class CommerceToolGateway{
 private final RestClient products,inventory,orders;private final InternalUserContextSignature users;private final InternalServiceSignature services;private final ObjectMapper json;
 public CommerceToolGateway(String productBase,String orderBase,byte[]secret,ObjectMapper json){this(productBase,productBase,orderBase,secret,json);}
 public CommerceToolGateway(String productBase,String inventoryBase,String orderBase,byte[]secret,ObjectMapper json){products=RestClient.builder().baseUrl(productBase).build();inventory=RestClient.builder().baseUrl(inventoryBase).build();orders=RestClient.builder().baseUrl(orderBase).build();users=new InternalUserContextSignature(secret,Clock.systemUTC(),Duration.ofSeconds(30));services=new InternalServiceSignature(secret,Clock.systemUTC(),Duration.ofSeconds(30));this.json=json;}
 public ToolEvidence product(String sku){ApiResponse<?>r=products.get().uri("/api/v1/products/{sku}",sku).retrieve().body(ApiResponse.class);ToolEvidence stock=inventory(sku);return evidence("PRODUCT_AND_INVENTORY_LOOKUP",Map.of("skuId",sku),Map.of("product",r==null?Map.of():Objects.requireNonNullElse(r.data(),Map.of()),"inventory",stock.resultJson()));}
 public ToolEvidence inventory(String sku){String path="/internal/v1/inventory/"+sku;Instant now=Instant.now();var m=new InternalServiceSignature.Metadata("ygh-ai-service","GET",path,now);ApiResponse<?>r=inventory.get().uri(path).header("X-YGH-Service","ygh-ai-service").header("X-YGH-Service-Timestamp",Long.toString(now.toEpochMilli())).header("X-YGH-Service-Signature",services.sign(m)).retrieve().body(ApiResponse.class);return evidence("INVENTORY_LOOKUP",Map.of("skuId",sku),r==null?null:r.data());}
 public ToolEvidence ownOrder(long user,String order){String path="/api/v1/orders/"+order,trace=uuid(),request=uuid();Instant now=Instant.now();var m=new InternalUserContextSignature.Metadata(Long.toString(user),List.of("USER"),List.of(),trace,request,"GET",path,now);ApiResponse<?>r=orders.get().uri(path).header("X-YGH-User-Id",Long.toString(user)).header("X-YGH-Roles","USER").header("X-YGH-Permissions","").header("X-Trace-Id",trace).header("X-Request-Id",request).header("X-YGH-User-Context-Timestamp",Long.toString(now.toEpochMilli())).header("X-YGH-User-Context-Signature",users.sign(m)).retrieve().body(ApiResponse.class);return evidence("OWN_ORDER_LOOKUP",Map.of("orderId",order),r==null?null:r.data());}
 private ToolEvidence evidence(String name,Map<String,String>args,Object result){try{String a=json.writeValueAsString(args),value=json.writeValueAsString(result);return new ToolEvidence(name,a,value,digest(value));}catch(Exception e){throw new IllegalStateException("tool result serialization failed",e);}}private static String digest(String x){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(x.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private static String uuid(){return UUID.randomUUID().toString().replace("-","");}public record ToolEvidence(String name,String argumentsJson,String resultJson,String digest){}
}
