CREATE TABLE system_role(id BIGINT NOT NULL,code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,name VARCHAR(100) NOT NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE,built_in BOOLEAN NOT NULL DEFAULT FALSE,version BIGINT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),PRIMARY KEY(id),UNIQUE KEY uk_system_role_code(code));
CREATE TABLE system_permission(id BIGINT NOT NULL,code VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,name VARCHAR(100) NOT NULL,resource_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),PRIMARY KEY(id),UNIQUE KEY uk_system_permission_code(code));
CREATE TABLE system_role_permission(role_id BIGINT NOT NULL,permission_id BIGINT NOT NULL,created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),PRIMARY KEY(role_id,permission_id),CONSTRAINT fk_system_rp_role FOREIGN KEY(role_id) REFERENCES system_role(id) ON DELETE CASCADE,CONSTRAINT fk_system_rp_permission FOREIGN KEY(permission_id) REFERENCES system_permission(id) ON DELETE RESTRICT);
CREATE TABLE system_user_authorization(user_id BIGINT NOT NULL,version BIGINT UNSIGNED NOT NULL DEFAULT 0,updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),PRIMARY KEY(user_id));
CREATE TABLE system_user_role(user_id BIGINT NOT NULL,role_id BIGINT NOT NULL,assigned_by BIGINT NOT NULL,assigned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),PRIMARY KEY(user_id,role_id),INDEX idx_system_user_role_role(role_id,user_id),CONSTRAINT fk_system_ur_auth FOREIGN KEY(user_id) REFERENCES system_user_authorization(user_id) ON DELETE CASCADE,CONSTRAINT fk_system_ur_role FOREIGN KEY(role_id) REFERENCES system_role(id) ON DELETE RESTRICT);
CREATE TABLE system_authorization_audit(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT NOT NULL,operator_user_id BIGINT NOT NULL,old_roles VARCHAR(2048) NOT NULL,new_roles VARCHAR(2048) NOT NULL,reason VARCHAR(500) NULL,created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),PRIMARY KEY(id),INDEX idx_system_auth_audit_user_created(user_id,created_at));
INSERT INTO system_role(id,code,name,enabled,built_in) VALUES(1,'USER','普通用户',TRUE,TRUE),(2,'EMPLOYEE','员工',TRUE,TRUE),(3,'ADMIN','系统管理员',TRUE,TRUE);
INSERT INTO system_permission(id,code,name,resource_type) VALUES(1,'profile:self:read','读取本人资料','USER'),(2,'profile:self:write','修改本人资料','USER'),(3,'system:rbac:write','管理角色权限','SYSTEM'),(4,'system:user:status','管理账号状态','AUTH');
INSERT INTO system_role_permission(role_id,permission_id) VALUES(1,1),(1,2),(2,1),(2,2),(3,1),(3,2),(3,3),(3,4);
