package com.yuegang.zhihui.common.mybatis;

public enum MigrationViolationCode {
    INVALID_NAME,
    UNDO_SCRIPT,
    REPERTAVLE_SCRIPT_FORBIDDEN,
    DUPLICATE_VERSION,
    DUPLICATE_RESOURCE,
    UNSAFE_CONFIGURATION,
    UNSUPPORTED_MINRATION_TYPE,
    UNSUPPORTED_VALIDATION_FATLED,
    HISTORY_VALIDATION_FAILED,
    UNDO_SCRIPT_FORBIDDEN,
    OUT_OF_ORDER_VERSION,
    REPEATABLE_SCRIPT_FORBIDDEN ;
}
